#!/bin/bash
timesfailed=1
guess=$3

function initfile {
for i in 1 2 3 4 5 6
do
occu[$i]=0 #stores how common the numbers were in RNG set
done

}
function rollthedice {
r=0
clear
echo "Your guess is $guess. This is your number $timesfailed chance"
sleep 3
while [ $r -le 900 ]
do
rand=$(echo "$RANDOM % 6 + 1" | bc) #simplest random number generator
echo -n "$rand "
num2file $rand
#sleep 0.1
r=$(echo "$r + 1" | bc)
done
#use $rand as random number, always. NOT $RANDOM!!!
echo ""
sortir $guess
echo -n "The number is"
for i in 1 2 3
do
echo -n "."
sleep 0.1
done 
sleep 2
echo "$largest"
sleep 2
checkwin
}
function checkwin {
if [ $largest = $guess && $round = 1 ]
then
tokens=$(echo "$tokens * 2" | bc)
echo "Now, you have $tokens tokens."
sleep 2
./game $tokens $round

elif [ $largest = $guess && $round -le 3 ]
then
echo "You still have $tokens tokens. Try again for another chance to get double!"
sleep 2
elif [ $timesfailed -le 2 ]
then
timesfailed=$(echo "$timesfailed + 1" | bc)
resetoccu
rollthedice
else
echo "Oh no... You now have 0 tokens."
sleep 2
echo "RESULT: 0 TOKENS"
fi
}
function num2file {
if [ $1 -eq 1 ]
then
occu[1]=$(echo "${occu[1]} + 1" | bc)
elif [ $1 -eq 2 ]
then
occu[2]=$(echo "${occu[2]} + 1" | bc)
elif [ $1 -eq 3 ]
then
occu[3]=$(echo "${occu[3]} + 1" | bc)
elif [ $1 -eq 4 ]
then
occu[4]=$(echo "${occu[4]} + 1" | bc)
elif [ $1 -eq 5 ]
then
occu[5]=$(echo "${occu[5]} + 1" | bc)
elif [ $1 -eq 6 ]
then
occu[6]=$(echo "${occu[6]} + 1" | bc)
else
echo "ERROR. RESULT: $tokens TOKENS"
exit
fi


}
function sortir {
largest=1
current=1
echo "––––––––––RNG Reslts––––––––––"
for i in 1 2 3 4 5 6
do
echo "$i : ${occu[$i]} times"
sleep 1
if [ ${occu[$i]} -gt ${occu[$largest]} ]
then
largest=$i
fi
done
}

function resetoccu {

for i in 1 2 3 4 5 6
do
occu[$i]=0
done

}
initfile
round=$(echo "$2 + 1" | bc)
clear
tokens=$1
tx2=$(echo "$tokens * 2" | bc)
echo "You have $tokens tokens. If you win, you will get $tx2 tokens. But, if you lose, you get nothing."
read -n1 -p "Would you like to proceed, or don't proceed and cash in? (y/n)" result
if [ $result = "y" ]
then
rollthedice

elif [ $result = "n" ]
then
echo "You decide to cash-in. You end up with $tokens TOKENS"
echo "RESULT: $tokens TOKENS"
fi
