#!/bin/bash
function yesno {

if [ $playing = "n" ] 2>/dev/null
then
echo "You have decided to cash in. You now have $tokens tokens."
echo "RESULT: $tokens TOKENS"
exit
elif [ $playing != "y" ] 2>/dev/null
then
echo "Try again, your input was not y or n"
read -n1 -p "Do you want to continue playing? (y/n) " playing
yesno
fi

}
clear
cat << eol
–––––A Dice Throwing Game–––––
RULES:
You start with 1 token.
You will be asked to pick a number between 1 and 6.
The computer will simulate throwing the dice three times.
If your number is correct within the three dice-throws, your pot is doubled.
If not, you lose the entire pot.

The RNG:
900 numbers, each between 1 and 6 are generated. The result of the RNG is the number
that appears most commonly in that set of 900 numbers.
–––––––––––––––––––––––––––––
eol


if [ ! $1 ]
then
tokens=1
else
tokens=$1 #starting tokens is equal to first argument
fi
if [ ! $2 ]
then
round=1
else
round=$2
fi
echo "You have $tokens tokens."
read -n1 -p "Do you want to continue playing? (y/n) " playing
yesno
printf "\nRound $round\nPick a number between 1 and 6"\!
read -n1 number
clear
if [ $number -a $number -ge 1 -a $number -le 6 ] 2>/dev/null
then
./number\ gen $tokens $round "$number"
else
echo "Sorry, your number is outside the range! Try again"
./game $tokens $round
fi
